### ISSUE TITLE
Compiling error: mising '../common/netcdf.hpp'

### ISSUE THREAD

**Issue by giswqs** [r-barnes/Barnes2019-DepressionHierarchy#1]
See the following error message when running the `make` command:

> make: *** No rule to make target '../common/netcdf.hpp', needed by 'a.out'.  Stop.

**Comment by r-barnes** [comment]
Thanks for pointing this out. I am working on it.

**Comment by awickert** [comment]
Thanks, @r-barnes and @giswqs.

@r-barnes: if you can send me the NetCDF library, it should be simple to include within this package... that is, unless you think that would be a bad idea for the architecture.

Is your netcdf.hpp the same as this? https://github.com/AppliedMathematicsANU/diamorse/blob/master/src/lib/netcdf.hpp

**Comment by r-barnes** [comment]
This should be fixed in the newest push. Build is now done with `cmake`.

**Comment by awickert** [comment]
Thanks, Richard!

CMAKE is complaining that:
```
submodules/richdem
```
does not contain a `CMakeLists.txt` file.

I copied `CMakeLists.txt` from the root directory there to see if that would fix, and that brought up directory-related errors in finding `dephier.exe`.

So... could you check that there isn't an additional `CMakeLists.txt` that isn't pushed?

**Comment by r-barnes** [comment]
I think this is fixed in the latest commits.
