### ISSUE TITLE
Retain projection information

### ISSUE THREAD

**Issue by awickert** [r-barnes/Barnes2019-DepressionHierarchy#10]
Suggested future improvement (I can volunteer myself to help, too): retaining projection information could be very helpful when building outputs from DH. This should be possible if exporting as NetCDF or GeoTiff.

**Comment by r-barnes** [comment]
This is a good idea.

Question: are we using NetCDF for anything? I have code for NetCDF in here because you and Kerry were using it, but if you're on GeoTIFF, I could remove it to simplify the dependency structure.

**Comment by awickert** [comment]
I am happy with any data structure. Thoughts:
* If removing NetCDF makes life easier, then yes, let's just go with GeoTiff and remove a dependency.
* NetCDF is a very common interchange format in climate sciences, so not a terrible compatibility... though at the cost of a dependency

I'm not a good enough C++ programmer to know if there is a way that is not horribly clunky to include optional dependencies.

Or honestly if it's worth it: if we choose to use DH as an engine connected to Python, for example, in the future, then Python handles I/O and all this is a little moot... so I'd take the path of least resistance here.

**Comment by r-barnes** [comment]
@awickert : RichDEM has a compilation option for the GDAL dependency which makes it easy to eliminate if it's not needed (such as wrapping with Python).

I've just pushed 35928790c7a4c8d63e244ed9184066ef31786c94 a commit that preserves the projection information in the output.
